server:
  port: 8888

spring:
  application:
    name: phc-world-config-service
  profiles:
    active: native
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\user\Documents\phc-world-native-file-repo
#        git:
#          uri: https://github.com/javamogi/spring-cloud-config
#          username: [username]
#          passphrase: [password]

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

